# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.create(title: 'Transportation')
Category.create(title: 'Traffic')
Category.create(title: 'Safety')
Category.create(title: 'Scary Person')
Category.create(title: 'MTA Stuff')
Category.create(title: 'Delays')
Category.create(title: 'Machines Broken')
Category.create(title: 'Sidewalks')
Category.create(title: 'Roads')
Category.create(title: 'Pollution')
Category.create(title: 'Garbage')
Category.create(title: 'Air Pollution')
Category.create(title: 'Noise Pollution')
Category.create(title: 'City Services')
Category.create(title: 'Salting Roads')
Category.create(title: 'Recycling')
Category.create(title: 'Issue at the Public Park')
Category.create(title: 'Rain Drainage')
Category.create(title: 'Slippery Road')
Category.create(title: 'Dangerous Intersection')
Category.create(title: 'Dangerous Turn')
Category.create(title: 'Dangerous Exit Ramp')
Category.create(title: 'Parking')
